kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: ens192
  annotations:
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/ens192
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "ens192",
      "type": "macvtap",
      "mtu": 1500
    }'

