apiVersion: k8s.cni.cncf.io/v1 
kind: NetworkAttachmentDefinition 
metadata: 
  annotations: 
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/ens192 
  name: macvtapnetwork 
spec: 
  config: '{"cniVersion": "0.3.1","type": "macvtap", "name": "macvtapnetwork", "mtu": 1500}'
