apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  labels:
    app: data-volume
  name: img-virtio-win
  namespace: default
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  source:
    http:
      url: http://minio.kubesphere-system.svc:9000/ecpaas-images/virtio-win-0.1.240.iso

