apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  labels:
    app: test-data-volume
  name: img-abc456
  namespace: default
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
  source:
    http:
      url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-i386.img
