apiVersion: virtualization.ecpaas.io/v1alpha1
kind: DiskVolume
metadata:
  name: vol-12345
  namespace: default
spec:
  resources:
    requests:
      storage: 20Gi
  source:
    image:
      name: img-u1804-cloudimg
      namespace: default
