apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "example-clone-dv"
spec:
  source:
      pvc:
        name: img-u1804-cloudimg
        namespace: default
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "20Gi"  # Size needs to be specified