apiVersion: virtualization.ecpaas.io/v1alpha1
kind: ImageTemplate
metadata:
  annotations:
    virtualization.ecpaas.io/alias-name: demo-image
  labels:
    virtualization.ecpaas.io/cpu-cores: "1"
    virtualization.ecpaas.io/image-memory: 8Gi
    virtualization.ecpaas.io/image-storage: 5Gi
    virtualization.ecpaas.io/os-family: windows
    virtualization.ecpaas.io/os-platform: windows
    virtualization.ecpaas.io/os-version: Windows_11_64bit
  name: img-windows-11-iso
  namespace: default
spec:
  resources:
    requests:
      storage: 20Gi
  source:
    http:
      url: http://minio.kubesphere-system.svc:9000/ecpaas-images/Windows.iso
