apiVersion: virtualization.ecpaas.io/v1alpha1
kind: ImageTemplate
metadata:
  annotations:
    virtualization.ecpaas.io/alias-name: demo-image
  labels:
    virtualization.ecpaas.io/cpu-cores: "1"
    virtualization.ecpaas.io/image-memory: 2Gi
    virtualization.ecpaas.io/image-storage: 20Gi
    virtualization.ecpaas.io/os-family: ubuntu
    virtualization.ecpaas.io/os-platform: linux
    virtualization.ecpaas.io/os-version: 20.04_LTS_64bit
  name: img-linux-iso-2004
  namespace: default
spec:
  resources:
    requests:
      storage: 20Gi
  source:
    http:
      url: http://minio.kubesphere-system.svc:9000/ecpaas-images/ubuntu-20.04.5-live-server-amd64.iso
