apiVersion: virtualization.ecpaas.io/v1alpha1
kind: ImageTemplate
metadata:
  annotations:
    kubesphere.io/alias-name: demo-image
  name: img-svc-5678
  namespace: default
spec:
  resources:
    requests:
      storage: 20Gi
  source:
    http:
      url: http://minio.minio-ecpaas.svc:9000/image/ubuntu-18.04-server-cloudimg-i386.img