apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-cstor-pvc-snap-u1804-cloudimg
spec:
  storageClassName: cstor-csi-disk
  dataSource:
    name: cstor-pvc-snap-u1804-cloudimg
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi